<?php
declare(strict_types=1);
$registry=sds_modules();$modules=$registry->all();$installationHistory=[];
try{$historyResult=$conn->query("SELECT i.* FROM sds_module_installations i INNER JOIN (SELECT module_id,MAX(id) id FROM sds_module_installations GROUP BY module_id) latest ON latest.id=i.id");if($historyResult)while($historyRow=$historyResult->fetch_assoc())$installationHistory[(string)$historyRow['module_id']]=$historyRow;}catch(Throwable $e){error_log('[SDS module history] '.$e->getMessage());}
$ready=0;$disabled=0;$problems=0;foreach($modules as $module){$status=$registry->status((string)$module['id']);if($status==='ready')$ready++;elseif($status==='disabled')$disabled++;else$problems++;}
$h=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$statusMap=['ready'=>['ok','Siap'],'disabled'=>['muted','Nonaktif'],'missing'=>['danger','Folder tidak tersedia'],'dependency_error'=>['warn','Dependensi belum siap'],'unknown'=>['danger','Tidak dikenal']];
include __DIR__.'/partials/shared/master_page_style.php';
?>
<style>.sds-modules-page .module-name{display:flex;align-items:flex-start;gap:.65rem}.sds-modules-page .module-icon{width:34px;height:34px;display:grid;place-items:center;background:#e7f1ff;color:#0d6efd;border:1px solid #cfe2ff;flex:0 0 auto}.sds-modules-page .module-icon svg{width:17px}.sds-modules-page .dependency-list{display:flex;gap:.25rem;flex-wrap:wrap}.sds-modules-page .package{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.75rem}.sds-modules-page .notice{border-left:4px solid #0d6efd;background:#f8f9fa;padding:.8rem 1rem;color:#495057;font-size:.82rem}</style>
<div class="sds-master-page sds-modules-page">
 <div class="sds-hero"><div><h2>Modul & Produk</h2><p>Registry pusat untuk paket fitur, versi, dependensi, dan entry point aplikasi.</p></div><div class="sds-hero-actions"><a href="pengaturan" class="btn btn-outline-primary btn-sm">Pengaturan Sistem</a></div></div>
 <div class="sds-stats three"><div class="sds-stat-card"><small>Modul Terdaftar</small><strong><?=count($modules)?></strong><span>Core dan produk tambahan</span></div><div class="sds-stat-card"><small>Siap Digunakan</small><strong><?=$ready?></strong><span>Folder dan dependensi lengkap</span></div><div class="sds-stat-card"><small>Perlu Perhatian</small><strong><?=$disabled+$problems?></strong><span>Nonaktif, hilang, atau dependensi bermasalah</span></div></div>
 <div class="sds-card"><div class="sds-card-header"><h5>Registry Modul</h5><span class="sds-mini">Konfigurasi: config/modules.php</span></div><div class="sds-card-body"><div class="notice mb-3">Tahap kompatibilitas aktif: folder dan URL lama belum dipindahkan. Registry ini menjadi fondasi installer paket dan lisensi pada tahap berikutnya.</div><div class="sds-table-wrap"><table class="sds-table wide"><thead><tr><th>Modul</th><th>Versi</th><th>Paket</th><th>Dependensi</th><th>Status</th><th class="text-end">Akses</th></tr></thead><tbody>
 <?php foreach($modules as $module):$id=(string)$module['id'];$status=$registry->status($id);$badge=$statusMap[$status]??$statusMap['unknown'];$dependencies=(array)$module['dependencies'];$history=$installationHistory[$id]??null;?>
 <tr><td><div class="module-name"><span class="module-icon"><i data-feather="package"></i></span><div><strong><?=$h($module['name'])?></strong><div class="sds-mini"><?=$h($module['description']??'')?></div></div></div></td><td><span class="sds-code">v<?=$h($module['version']??'-')?></span><?php if($history):?><div class="sds-mini mt-1">Paket v<?=$h($history['version'])?> · <?=$h(date('d/m/Y H:i',strtotime((string)$history['installed_at'])))?></div><?php endif;?></td><td><span class="package"><?=$h($module['package']??$id)?></span></td><td><div class="dependency-list"><?php if(!$dependencies):?><span class="sds-mini">Mandiri</span><?php endif;?><?php foreach($dependencies as $dependency):?><span class="sds-badge muted"><?=$h($dependency)?></span><?php endforeach;?></div></td><td><span class="sds-badge <?=$badge[0]?>"><?=$badge[1]?></span><?php if(($history['status']??null)==='failed'):?><div class="sds-mini text-danger mt-1">Instalasi terakhir gagal</div><?php endif;?><?php if($missing=$registry->missingDependencies($id)):?><div class="sds-mini mt-1">Kurang: <?=$h(implode(', ',$missing))?></div><?php endif;?></td><td class="text-end"><?php if($registry->isEnabled($id)&&!empty($module['entry'])):?><a class="btn btn-outline-primary btn-sm" href="<?=$h(sds_base_url((string)$module['entry']))?>" <?=$id!=='core'?'target="_blank" rel="noopener"':''?>>Buka</a><?php else:?><button class="btn btn-light btn-sm" disabled>Tidak tersedia</button><?php endif;?></td></tr>
 <?php endforeach;?></tbody></table></div></div></div>
</div>
