<?php
$page='teachers_rfid';
require_once __DIR__.'/../../config/perpus.php';
sds_perpus_ensure_schema($conn);
if(empty($_SESSION['csrf_teacher_rfid']))$_SESSION['csrf_teacher_rfid']=bin2hex(random_bytes(24));
$q=trim((string)($_GET['q']??''));$card=trim((string)($_GET['kartu']??''));$status=trim((string)($_GET['status']??''));if(!in_array($card,['terpasang','kosong'],true))$card='';if(!in_array($status,['aktif','nonaktif'],true))$status='';
$where=['1=1'];$params=[];$types='';if($q!==''){$where[]='(p.nama_lengkap LIKE ? OR p.nip LIKE ? OR p.jabatan LIKE ? OR kr.uid LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like,$like);$types.='ssss';}if($card==='terpasang')$where[]='kr.id IS NOT NULL';elseif($card==='kosong')$where[]='kr.id IS NULL';if($status==='aktif')$where[]="p.active='Y'";elseif($status==='nonaktif')$where[]="p.active='N'";
$sql="SELECT p.pegawai_id,p.nip,p.nama_lengkap,p.jabatan,p.avatar,p.active,kr.uid,kr.tanggal_terbit FROM pegawai p LEFT JOIN kartu_rfid kr ON kr.pemilik_tipe='pegawai' AND kr.pemilik_id=p.pegawai_id WHERE ".implode(' AND ',$where).' ORDER BY CASE WHEN kr.id IS NULL THEN 0 ELSE 1 END,p.nama_lengkap';$stmt=$conn->prepare($sql);if($types){$refs=[$types];foreach($params as $i=>&$v)$refs[]=&$v;call_user_func_array([$stmt,'bind_param'],$refs);}$stmt->execute();$rows=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
$stats=['total'=>0,'assigned'=>0,'empty'=>0,'active'=>0];$r=$conn->query("SELECT COUNT(*) total,SUM(kr.id IS NOT NULL) assigned,SUM(kr.id IS NULL) empty,SUM(p.active='Y') active FROM pegawai p LEFT JOIN kartu_rfid kr ON kr.pemilik_tipe='pegawai' AND kr.pemilik_id=p.pegawai_id");if($r){$x=$r->fetch_assoc();$stats=['total'=>(int)$x['total'],'assigned'=>(int)$x['assigned'],'empty'=>(int)$x['empty'],'active'=>(int)$x['active']];}
require __DIR__.'/partials/shared/master_page_style.php';
?>
<style>.teacher-rfid .filter-grid{display:grid;grid-template-columns:minmax(240px,1.5fr) minmax(150px,.7fr) minmax(150px,.7fr) auto auto;gap:.5rem}.teacher-rfid .scan-input{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:1.05rem}.teacher-rfid .name{font-weight:700;color:#1e293b}.teacher-rfid .meta{font-size:.78rem;color:#64748b}@media(max-width:800px){.teacher-rfid .filter-grid{grid-template-columns:1fr 1fr}.teacher-rfid .filter-grid .search{grid-column:1/-1}}@media(max-width:600px){.teacher-rfid .filter-grid{grid-template-columns:1fr}}</style>
<div class="sds-master-page teacher-rfid"><div class="sds-hero"><div><h2>Kode Kartu Pengajar & Pegawai</h2><p>Pasangkan kartu RFID pegawai pada master SDS agar dapat digunakan Absensi dan Perpustakaan.</p></div><div class="sds-hero-actions"><a href="teachers" class="btn btn-secondary">Data Pengajar & Pegawai</a><a href="rfid_history?jenis=pegawai" class="btn btn-outline-primary">Riwayat Kartu</a><a href="teachers_rfid?kartu=kosong" class="btn btn-primary">Belum Terpasang</a></div></div>
<?php if(!empty($_SESSION['success'])):?><div class="alert alert-success"><?=htmlspecialchars((string)$_SESSION['success']);unset($_SESSION['success']);?></div><?php endif;?><?php if(!empty($_SESSION['error'])):?><div class="alert alert-danger"><?=htmlspecialchars((string)$_SESSION['error']);unset($_SESSION['error']);?></div><?php endif;?>
<div class="sds-stats"><div class="sds-stat-card"><small>Total Pegawai</small><strong><?=number_format($stats['total'],0,',','.')?></strong><span>Seluruh data master pegawai</span></div><div class="sds-stat-card"><small>Kartu Terpasang</small><strong><?=number_format($stats['assigned'],0,',','.')?></strong><span>UID aktif pada kartu_rfid</span></div><div class="sds-stat-card"><small>Belum Terpasang</small><strong><?=number_format($stats['empty'],0,',','.')?></strong><span>Perlu dipasangkan reader RFID</span></div><div class="sds-stat-card"><small>Pegawai Aktif</small><strong><?=number_format($stats['active'],0,',','.')?></strong><span>Status aktif pada master SDS</span></div></div>
<div class="card"><div class="card-header"><form class="filter-grid"><input class="form-control form-control-sm search" name="q" value="<?=htmlspecialchars($q)?>" placeholder="Cari nama, NIP, jabatan, RFID..."><select class="form-select form-select-sm" name="kartu"><option value="">Semua Kartu</option><option value="terpasang" <?=$card==='terpasang'?'selected':''?>>Terpasang</option><option value="kosong" <?=$card==='kosong'?'selected':''?>>Belum Terpasang</option></select><select class="form-select form-select-sm" name="status"><option value="">Semua Status</option><option value="aktif" <?=$status==='aktif'?'selected':''?>>Aktif</option><option value="nonaktif" <?=$status==='nonaktif'?'selected':''?>>Nonaktif</option></select><button class="btn btn-sm btn-primary">Tampilkan</button><a href="teachers_rfid" class="btn btn-sm btn-outline-secondary">Reset</a></form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Pengajar/Pegawai</th><th>Jabatan</th><th>Kode Kartu</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="5" class="text-center text-muted py-4">Data tidak ditemukan.</td></tr><?php endif;?><?php foreach($rows as $r):$payload=htmlspecialchars(json_encode($r,JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8');?><tr><td><div class="name"><?=htmlspecialchars($r['nama_lengkap'])?></div><div class="meta">NIP: <?=htmlspecialchars($r['nip']?:'-')?></div></td><td><?=htmlspecialchars($r['jabatan']?:'-')?></td><td><?=trim((string)$r['uid'])!==''?'<code>'.htmlspecialchars($r['uid']).'</code>':'<span class="badge bg-warning text-dark">Belum ada kartu</span>'?></td><td><?=$r['active']==='Y'?'<span class="badge bg-success">Aktif</span>':'<span class="badge bg-secondary">Nonaktif</span>'?></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-row="<?=$payload?>" onclick="openTeacherCard(this)"><?=$r['uid']?'Edit Kartu':'Scan Kartu'?></button></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="modal fade" id="teacherCardModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post" action="teachers_rfid_input"><div class="modal-header"><h5 class="modal-title">Kartu Pengajar/Pegawai</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf_teacher_rfid'])?>"><input type="hidden" name="pegawai_id" id="teacherCardId"><input type="hidden" name="action" id="teacherCardAction" value="save"><div class="alert alert-light border"><strong id="teacherCardName">-</strong><div class="small text-muted" id="teacherCardNip">-</div></div><label class="form-label">UID Kartu RFID</label><input class="form-control scan-input" name="rfid_uid" id="teacherCardUid" autocomplete="off" placeholder="Tempel kartu pada reader"><div class="form-text">Satu kartu hanya dapat dipakai oleh satu siswa atau pegawai.</div></div><div class="modal-footer justify-content-between"><button class="btn btn-danger" id="teacherCardRemove" type="submit" onclick="document.getElementById('teacherCardAction').value='remove';return confirm('Lepaskan kartu dari pegawai ini?')">Lepaskan Kartu</button><div><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button> <button class="btn btn-primary" type="submit" onclick="document.getElementById('teacherCardAction').value='save'">Simpan</button></div></div></form></div></div></div>
<script>function tcModal(){const e=document.getElementById('teacherCardModal');if(!window.bootstrap)return null;return typeof bootstrap.Modal.getOrCreateInstance==='function'?bootstrap.Modal.getOrCreateInstance(e):new bootstrap.Modal(e)}function openTeacherCard(btn){const r=JSON.parse(btn.dataset.row||'{}');document.getElementById('teacherCardId').value=r.pegawai_id||0;document.getElementById('teacherCardName').textContent=r.nama_lengkap||'-';document.getElementById('teacherCardNip').textContent='NIP: '+(r.nip||'-')+' · '+(r.jabatan||'-');document.getElementById('teacherCardUid').value=r.uid||'';document.getElementById('teacherCardRemove').style.visibility=r.uid?'visible':'hidden';const m=tcModal();if(m){m.show();setTimeout(()=>document.getElementById('teacherCardUid').focus(),250)}}</script>
