<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$target=null;foreach(array_slice($argv,1) as $arg)if(str_starts_with($arg,'--target='))$target=substr($arg,9);$target=$target?realpath($target):false;if(!$target||!is_dir($target)||!is_file($target.'/config/runtime.php'))throw new RuntimeException('Target layout tidak valid.');
$moves=['absensi'=>'modules/attendance/app','anjungan'=>'modules/kiosk/app','mkantin'=>'modules/canteen/app','emoney'=>'modules/emoney/app','perpustakaan'=>'modules/library/app'];
foreach($moves as $source=>$destination){$from=$target.'/'.$source;$to=$target.'/'.$destination;if(!is_dir($from))continue;if(is_dir($to))throw new RuntimeException('Tujuan layout sudah berisi folder: '.$destination);if(!is_dir(dirname($to))&&!mkdir(dirname($to),0750,true)&&!is_dir(dirname($to)))throw new RuntimeException('Folder modul gagal dibuat.');if(!rename($from,$to))throw new RuntimeException('Gagal memindahkan '.$source);}
$configFiles=glob($target.'/config/*.php')?:[];$moduleIds=['attendance','kiosk','canteen','emoney','library'];
foreach($moduleIds as $id){$base=$target.'/modules/'.$id;if(!is_dir($base))continue;$configDir=$base.'/config';$vendorDir=$base.'/vendor';if(!is_dir($configDir))mkdir($configDir,0750,true);if(!is_dir($vendorDir))mkdir($vendorDir,0750,true);foreach($configFiles as $configFile){$name=basename($configFile);$require=$name==='runtime.php'?'require_once':'require';$wrapper="<?php\nreturn {$require} dirname(__DIR__,3).'/config/{$name}';\n";file_put_contents($configDir.'/'.$name,$wrapper,LOCK_EX);}file_put_contents($base.'/db.php',"<?php\nreturn require dirname(__DIR__,2).'/db.php';\n",LOCK_EX);file_put_contents($base.'/config.php',"<?php\nreturn require dirname(__DIR__,2).'/config.php';\n",LOCK_EX);file_put_contents($vendorDir.'/autoload.php',"<?php\nreturn require dirname(__DIR__,3).'/vendor/autoload.php';\n",LOCK_EX);$bootstrap="<?php\ndeclare(strict_types=1);\ndefine('SDS_MODULE_ID','{$id}');\nrequire_once dirname(__DIR__,2).'/config/runtime.php';\n";file_put_contents($base.'/bootstrap.php',$bootstrap,LOCK_EX);}
$rules=[
 'absensi'=>'modules/attendance/app','anjungan'=>'modules/kiosk/app','mkantin'=>'modules/canteen/app','emoney'=>'modules/emoney/app','perpustakaan'=>'modules/library/app',
];
$original=is_file($target.'/.htaccess')?(string)file_get_contents($target.'/.htaccess'):'';$header="# SDS modular compatibility routes\nRewriteEngine On\n";foreach($rules as $url=>$path)$header.='RewriteRule ^'.preg_quote($url,'#').'(?:/(.*))?$ '.$path.'/$1 [L,QSA]'."\n";$header.='RewriteRule ^(formulir|form|upload|proses_map|ambil_field_aktif|cetak_daftar_ulang|cetak_dokumen_daftar_ulang|instructions|progress)(?:\.php)?/?$ modules/enrollment/app/$1.php [L,QSA]'."\n";if(!str_contains($original,'# SDS modular compatibility routes'))file_put_contents($target.'/.htaccess',$header."\n".$original,LOCK_EX);
$enrollment=['formulir','form','upload','proses_map','ambil_field_aktif','cetak_daftar_ulang','cetak_dokumen_daftar_ulang','instructions','progress'];$router="<?php\n\$path=ltrim((string)parse_url(\$_SERVER['REQUEST_URI']??'/',PHP_URL_PATH),'/');\$routeName=(string)preg_replace('/\\.php$/i','',\$path);\$enrollment=".var_export($enrollment,true).";if(in_array(\$routeName,\$enrollment,true))\$path='modules/enrollment/app/'.\$routeName.'.php';\$map=".var_export($rules,true).";foreach(\$map as \$prefix=>\$destination)if(\$path===\$prefix||str_starts_with(\$path,\$prefix.'/')){\$path=\$destination.substr(\$path,strlen(\$prefix));break;}\$file=__DIR__.'/'.\$path;if(is_dir(\$file))\$file=rtrim(\$file,'/').'/index.php';if(is_file(\$file)){if(strtolower(pathinfo(\$file,PATHINFO_EXTENSION))==='php'){chdir(dirname(\$file));require \$file;}else{readfile(\$file);}return true;}return false;\n";file_put_contents($target.'/router.php',$router,LOCK_EX);
echo 'LAYOUT MODULAR SELESAI: '.$target.PHP_EOL;
