<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
date_default_timezone_set('Asia/Jakarta');
$root=dirname(__DIR__);$requested='attendance,emoney,canteen,library,kiosk';$skipBuild=false;foreach(array_slice($argv,1) as $arg){if(str_starts_with($arg,'--modules='))$requested=substr($arg,10);elseif($arg==='--skip-build')$skipBuild=true;}$modules=array_values(array_unique(array_filter(array_map('trim',explode(',',$requested)))));$definitions=require $root.'/packaging/packages.php';foreach($modules as $module)if($module==='core'||!isset($definitions[$module])||str_contains((string)$definitions[$module]['version'],'dev'))throw new RuntimeException('Modul rilis tidak valid atau belum produksi: '.$module);if(in_array('canteen',$modules,true)&&!in_array('emoney',$modules,true))$modules[]='emoney';$targets=['core',...$modules];if(!$skipBuild){$command=[PHP_BINARY,$root.'/tools/build-packages.php','--module='.implode(',',$targets)];$pipes=[];$process=proc_open($command,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);if(!is_resource($process))throw new RuntimeException('Builder paket gagal dimulai.');fclose($pipes[0]);$stdout=stream_get_contents($pipes[1]);fclose($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[2]);$code=proc_close($process);if($code!==0)throw new RuntimeException('Builder paket gagal: '.trim($stderr?:$stdout));echo $stdout;}
$release=$root.'/storage/releases/'.date('Ymd-His').'-'.bin2hex(random_bytes(3));$app=$release.'/app';$packageDir=$release.'/packages';foreach([$app,$packageDir] as $dir)if(!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Folder rilis gagal dibuat.');$catalog=['format'=>1,'layout'=>'modular-app','runtime'=>'app','created_at'=>date(DATE_ATOM),'modules'=>[]];
foreach($targets as $module){$prefix=$definitions[$module]['package'].'-'.$definitions[$module]['version'].'-';$matches=glob($root.'/storage/packages/'.$prefix.'*.zip')?:[];usort($matches,static fn($a,$b)=>filemtime($b)<=>filemtime($a));$source=$matches[0]??null;if(!$source)throw new RuntimeException('Paket hasil build tidak ditemukan: '.$module);$destination=$packageDir.'/'.basename($source);copy($source,$destination);copy($source.'.sha256',$destination.'.sha256');$zip=new ZipArchive();if($zip->open($source)!==true)throw new RuntimeException('Paket gagal dibuka: '.$module);if(!$zip->extractTo($app))throw new RuntimeException('Paket gagal dirakit: '.$module);$metadata=json_decode((string)$zip->getFromName('package.json'),true);$zip->close();$catalog['modules'][$module]=['file'=>'packages/'.basename($source),'sha256'=>hash_file('sha256',$source),'package'=>$metadata['package'],'version'=>$metadata['version'],'dependencies'=>$module==='core'?[]:(json_decode((string)file_get_contents($app.'/modules/'.$module.'/module.json'),true)['dependencies']??[])];}
$pipes=[];$process=proc_open([PHP_BINARY,$root.'/tools/arrange-modular-layout.php','--target='.$app],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);if(!is_resource($process))throw new RuntimeException('Penataan layout modular gagal dimulai.');fclose($pipes[0]);$layoutOut=stream_get_contents($pipes[1]);fclose($pipes[1]);$layoutError=stream_get_contents($pipes[2]);fclose($pipes[2]);if(proc_close($process)!==0)throw new RuntimeException('Penataan layout modular gagal: '.trim($layoutError?:$layoutOut));
file_put_contents($release.'/catalog.json',json_encode($catalog,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL,LOCK_EX);file_put_contents($release.'/README.txt',"SDS Distribution\nSalin isi folder app ke document root Apache lalu akses /install/.\nSource fitur berada di modules/<id>/app.\nURL lama tetap dipertahankan oleh routing kompatibilitas.\nPaket dan checksum asli tersedia di folder packages.\n",LOCK_EX);echo 'RELEASE: '.$release.PHP_EOL;
