<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);require $root.'/config/runtime.php';$definitions=require $root.'/packaging/schema-products.php';$db=sds_mysqli('main');$tables=[];$result=$db->query('SHOW FULL TABLES WHERE Table_type = \'BASE TABLE\'');while($row=$result->fetch_row())$tables[]=(string)$row[0];sort($tables);$owners=[];$unassigned=[];
foreach($tables as $table){$matches=[];foreach($definitions as $module=>$definition){if(in_array($table,(array)($definition['tables']??[]),true))$matches[]=$module;foreach((array)($definition['patterns']??[]) as $pattern)if(preg_match($pattern,$table)){if(!in_array($module,$matches,true))$matches[]=$module;break;}}if(count($matches)>1)throw new RuntimeException('Tabel memiliki beberapa pemilik: '.$table.' ('.implode(', ',$matches).')');if(!$matches)$unassigned[]=$table;else$owners[$matches[0]][]=$table;}
// Semua tabel yang tidak dikenali tetap masuk Core, tetapi dilaporkan agar dapat ditinjau.
foreach($unassigned as $table)$owners['core'][]=$table;sort($owners['core']);
$cfg=sds_database_config('main');$xamppRoot=dirname(dirname(PHP_BINARY));$binary=$xamppRoot.'/mysql/bin/mysqldump.exe';if(!is_file($binary))$binary='mysqldump';$escape=static fn(string $value):string=>'"'.str_replace(['\\','"'],['\\\\','\\"'],$value).'"';$defaultsFile=tempnam(sys_get_temp_dir(),'sds-schema-');if($defaultsFile===false)throw new RuntimeException('Konfigurasi sementara gagal dibuat.');$defaults="[client]\n".'host='.$escape((string)$cfg['host'])."\n".'port='.(int)$cfg['port']."\n".'user='.$escape((string)$cfg['username'])."\n".'password='.$escape((string)$cfg['password'])."\ndefault-character-set=utf8mb4\n";$outputDir=$root.'/install/schema';if(!is_dir($outputDir)&&!mkdir($outputDir,0750,true)&&!is_dir($outputDir))throw new RuntimeException('Folder schema gagal dibuat.');
try{file_put_contents($defaultsFile,$defaults,LOCK_EX);@chmod($defaultsFile,0600);foreach(array_keys($definitions) as $module){$moduleTables=$owners[$module]??[];sort($moduleTables);if(!$moduleTables){echo strtoupper($module).": 0 tabel (dilewati)\n";continue;}$moduleOutputDir=$module==='core'?$outputDir:$root.'/modules/'.$module.'/database';if(!is_dir($moduleOutputDir)&&!mkdir($moduleOutputDir,0750,true)&&!is_dir($moduleOutputDir))throw new RuntimeException('Folder schema modul gagal dibuat: '.$module);$output=$moduleOutputDir.'/'.($module==='core'?'core.sql':'schema.sql');$command=[$binary,'--defaults-extra-file='.$defaultsFile,'--no-data','--routines=false','--events=false','--skip-triggers','--skip-comments','--skip-dump-date','--default-character-set=utf8mb4',(string)$cfg['database'],'--tables',...$moduleTables,'--result-file='.$output];$pipes=[];$process=proc_open($command,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);if(!is_resource($process))throw new RuntimeException('mysqldump gagal dimulai.');fclose($pipes[0]);$stdout=stream_get_contents($pipes[1]);fclose($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[2]);$code=proc_close($process);if($code!==0)throw new RuntimeException('Schema '.$module.' gagal: '.trim($stderr?:$stdout));$schema=(string)file_get_contents($output);$schema=preg_replace('/\s+AUTO_INCREMENT=\d+/i','',$schema);if($schema===null||file_put_contents($output,$schema,LOCK_EX)===false)throw new RuntimeException('Normalisasi schema gagal: '.$module);$hash=hash_file('sha256',$output);file_put_contents($output.'.sha256',$hash.'  '.basename($output).PHP_EOL,LOCK_EX);echo strtoupper($module).': '.count($moduleTables).' tabel | '.$hash.PHP_EOL;}}finally{@unlink($defaultsFile);$db->close();}
if($unassigned)echo 'REVIEW CORE (belum memiliki aturan khusus): '.implode(', ',$unassigned).PHP_EOL;
